ALL: TARGET0 TARGET1 TARGET2 TARGET3

TARGET0 : play_again0.c
	gcc -o play_again0.o play_again0.c
TARGET1 : play_again1.c
	gcc -o play_again1.o play_again1.c
TARGET2 : play_again2.c
	gcc -o play_again2.o play_again2.c
TARGET3 : play_again3.c
	gcc -o play_again3.o play_again3.c

clean : 
	rm play_again*.o
